(define (sum term a next b)
  (define (iter a result)
    (if (> a b)
        result
        (iter (next a)
              (+ (iterm a) result))))
  (iter a 0))
(define (integral f a b n)
  (define h (/ (- b a) n))
  (define (choice k)
    (cond ((or (= k 0) (= k n)) 1)
          ((even? k) 2)
          (else 4)))
  (define (y k)
    (f (+ a (* k h))))
  (define (term k)
    (* (choice k) (y k)))
  (define (next k)
    (+ 1 k))
  (* (/ h 3)
     (sum term 0 next n)))
(define (cube x)
  (* x x x))(define size 2)

