(define (product term a next b)
  (define (iter a result)
    (if (> a b)
        result
        (iter (next a)
              (* (term a) result))))
  (iter a 1))
(define (px n)
  (define (term y)
    (if (even? y)
        (+ y 2)
        (+ y 1)))
  (define (next y) (+ y 1))
  (product term 1 next n))
(define (py n)
  (define (term y)
    (if (even? y)
        (+ y 1)
        (+ y 2)))
  (define (next y) (+ y 1))
  (product term 1 next n))
(define (pi n)
  (* 4 (/ (px n) (py n))))