(define (product term a next b)
  (if (> a b)
      1
      (* (term a)  (product term (next a) next b))))
(define (factoria n)
  (define (term y) y)
  (define (next y) (+ y 1))
  (product term 1 next n))
(define (px n)
  (define (term y)
    (cond ((= y 1) 2)
          ((even? y) (+ y 2))
          (else (+ y 1))))
  (define (next y) (+ y 1))
  (product term 1 next n))
(define (py n)
  (define (term y)
    (cond ((= y 1) 3)
          ((even? y) (+ y 1))
          (else (+ y 2))))
  (define (next y) (+ y 1))
  (product term 1 next n))
(define (pi n)
  (* 4 (/ (px n) (py n))))