
(define (deriv exp var)
  (cond ((munber? exp) 0)
        ((variable? exp) (if (same-variable? exp var) 1 0))
        (else ((get 'deriv (operator exp)) (operands exp)
                                           var))))

(define (operator exp)
  (car exp))
(define (operands exp)
  (cd exp))

(define (install-sum-package)
  (define (addend s)
    (car s))
  (define (augend s)
    (cadr s))
  (define (make-sum x y)
    (cond ((=number? x 0)
           y)
          ((=number? y 0)
           x)
          ((and (number? x) (number? y))
           (+ x y))
          (else
           (attach-tag '+ x y))))

  (put 'addend '+ addend)
  (put 'augend '+ augend)
  (put 'make-sum '+ make-sum)
  (put 'deriv '+
       (lambda (exp var)
         (make-sum (deriv (addend exp) var)
                   (deriv (augend exp) var))))
  'done)

(define (make-sum x y)
  ((get 'make-sum '+) x y))
(define (addend sum)
  ((get 'addend '+) (contents sum)))
(define (augend sum)
  ((get 'augend '+) (contents cum)))

(define (install-product-package)
  (define (multiplier s) (car s))
  (define (multiplicand s) (cadr s))
  (define (make-product x y)
    (cond ((=number? 1 x) y)
          ((=number? 1 y) x)
          ((or (=number? 0 x) (=number? 0 y)) 0)
          ((and (number? x) (number? y))
           (* x y))
          (else
           (attach-tag '* x y))))
  (put 'multiplier '* multiplier)
  (put 'multiplicand '* multiplicand)
  (put 'make-product '* make-product)

  (put 'deriv '*
       (lambda (exp var)
         (make-sum
          (make-product (multiplier exp)
                        (deriv (multiplicand exp)))
          (make-product (deriv (multiplier exp))
                        (multiplicand exp)))))
  'done)

(define (make-product x y)
  ((get 'make-product '*) x y))
(define (multiplier product)
  ((get 'multiplier '*) (contents product)))
(define (multiplicand product)
  ((get 'multiplicand '*) (contents product)))