(define (let*? exp) (tagged-list? exp 'let*))
(define (let*-body exp) (caddr exp))
(define (let*-inits exp) (cadr exp))
(define (let*->nested-lets exp)
  (let ((inits (let*-inits exp))
        (body (let*body exp)))
    (define (make-lets exp)
      (if (null? exp)
          body
          (list 'let (list (car exp)) (make-lets (cdr exps)))))
    (make-lets inits)))